# Generated by Django 4.1.1 on 2024-09-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
